### ISSUE TITLE
Searching for active objects

### ISSUE THREAD

**Issue by andreaskring** [magenta-aps/mox#14]
A suggestion for a new feature. Currently, it is not possible to search directly for e.g. active organisation units, i.e. it is not possible to perform a request like this:
```
GET http://mox/organisation/organisationenhed?gyldighed=Aktiv&virkningfra=...&virkningtil=...
```
It would be nice if this feature could be implemented.

**Comment by danchr** [comment]
I believe I fixed that in https://github.com/magenta-aps/mox/commit/1cda00f118bef5ec9c46fc879a08636442daa278, which we then released as 0.3.1. Which version are you running?

**Comment by danchr** [comment]
(FWIW we rely on this functionality as part of rendering the tree view.)

**Comment by danchr** [comment]
Fixed, as described earlier. Much earlier…
