### ISSUE TITLE
sudo dependency in install.sh

### ISSUE THREAD

**Issue by JosefAssad** [magenta-aps/mox#2]
I'm guessing this is to be ubuntu friendly?

It seems more natural to me to require root privileges; Ubuntistas can just sudo su. On this Debian box I don't particularly want to configure sudo to install this software.

**Comment by agger-magenta** [comment]
We'll consider this in future versions of the installer; for now, I suggest you remove the "sudo" from the relevant commands and run it as root.

Do note, though, that this means you'll probably have to chown some stuff afterwards to avoid root ownership of too much,

**Comment by agger-magenta** [comment]
But basically, the rationale is to run as much as possible as an unprivileged user.

Also note that this system was built on Ubuntu 14.04 and has not been tested on other systems. Making it more Debian-friendly or supporting other package managers such as yum or BSD ports would be nice, but until now we haven't had the need or the resources to do so.

**Comment by JosefAssad** [comment]
I agree re. resources and prioritisation, I'm just giving feedback. It isn't a high priority issue, I already got it working. I'm just noting the issue so we have a place to talk about it.

**Comment by agger-magenta** [comment]
And very appropriately, thanks for the feedback! :-)

**Comment by danchr** [comment]
Closing; the old installer is dead — although this issue might persist.
