### ISSUE TITLE
Installing - requirement

### ISSUE THREAD

**Issue by mariushart** [magenta-aps/mox#3]
Installation requires that Oracle JAVA is already installed.
If not installation will fail with 

> Error: JAVA_HOME is not defined correctly.
>   We cannot execute /usr/lib/jvm/java-8-oracle//bin/java /srv/mox

Solution idea: add Oracle JAVA to description of dependencies/requirements before installation

**Comment by agger-magenta** [comment]
Yes, this is a bug.

In fact, the default installation should _not_ install Oracle Java. Originally, it didn't but used OpenJDK - there is absolutely no good reason to require Oracle Java.  Now that it does, of course, it should also perform a proper check to see if it's installed.

In other words, the installation script should be changed to expect OpenJDK and should install that gracefully by itself.

**Comment by Lapeth** [comment]
The installer already makes an effort in install.sh line 71, but yes, it could be better.

**Comment by agger-magenta** [comment]
Anyway, we can fix that as part of getting rid of the use of Oracle's Java. Of course, our system should work with any compliant Java implementation, but OpenJDK is, according to Oracle itself, the reference implementation and should be the default.

**Comment by Lapeth** [comment]
I'll make a feature branch and work on a solution

**Comment by agger-magenta** [comment]
Thanks! :-)

**Comment by Lapeth** [comment]
It is now on feature/ticket16348_java8 and merged to testing

**Comment by danchr** [comment]
…and that branch was merged into master earlier this year.
