### ISSUE TITLE
Cant start moxrestfrontend after new install. 

### ISSUE THREAD

**Issue by Hypser** [magenta-aps/mox#4]
After installing from the Quick install with no problem, i get this error, trying to start moxrestfrontend.

mox@moxtest:/srv/mox$ sudo service moxrestfrontend start
Failed to start moxrestfrontend.service: Unit moxrestfrontend.service not found.

How come?

**Comment by Lapeth** [comment]
Hmm... I assume you checked out the master branch.
Does the file /etc/init/moxrestfrontend.conf exist on your system?

**Comment by Hypser** [comment]
root@moxtest:~# ls -al /etc/init/mox*
-rw-r--r-- 1 root root 181 Aug 18 08:48 /etc/init/moxrestfrontend.conf
-rw-r--r-- 1 root root 160 Aug 18 08:48 /etc/init/moxtabel.conf

**Comment by Lapeth** [comment]
Can you try checking out the development branch and re-run the install?

**Comment by Hypser** [comment]
That doesnt work either.

Iam getting this qustion now: 
Path for certificate [/etc/apache2/certs/magenta-aps.dk.crt]:

And the default answer to it doesnt work.

**Comment by agger-magenta** [comment]
Thanks for your work on testing this! 

We discussed this issue at a meeting yesterday and will be fixing the system before to long, so the installer will work out of the box and will handle SSL certificates etc. correctly.

We'll keep you posted. :)

**Comment by agger-magenta** [comment]
To address the problem here and now, I propose you generate a self-signed certificate or disable SSL.

**Comment by Hypser** [comment]
But i dont see how that is gonna soled the problem in the first place, with the "Unit moxrestfrontend.service not found." message when i start the moxfrontend.

**Comment by Hypser** [comment]
What is the ETA on the new installer?

**Comment by Lapeth** [comment]
The development branch has newer code, that should resolve your original issue. I recommend adding a self-signed certificate and providing the path to it during install.

**Comment by Hypser** [comment]
What is this now?

Path for new keystore [/opt/wso2is-5.0.0/repository/resources/security/newkeystore.jks]:
Name of new keystore must not be empty

Path for new keystore [/opt/wso2is-5.0.0/repository/resources/security/newkeystore.jks]:

**Comment by agger-magenta** [comment]
We had to do some adjustments to the default installation of WSO2. If you're planning to run without SAML validation you can ignore this. If not, you should enter a valid path for the keystore.

**Comment by agger-magenta** [comment]
... or maybe skip this part of the installation if you don't require WSO2 to run with a valid SSL certificate.

**Comment by Hypser** [comment]
How can i skip it?

**Comment by danchr** [comment]
Fixed in January; closing.
